# Generated by Django 5.2.6 on 2025-11-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='statut_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
