# Generated by Django 5.2.8 on 2025-11-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('HOTEL', 'Hotel'), ('APARTMENT', 'Apartment'), ('VILLA', 'Villa')], default='HOTEL', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=2)),
                ('equipement', models.TextField(blank=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(max_length=100)),
                ('numero_vol', models.CharField(max_length=50)),
                ('aeroport_arrive', models.CharField(max_length=100)),
                ('aeroport_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('date_depart', models.DateTimeField()),
                ('date_arrive', models.DateTimeField()),
                ('duree', models.DurationField(blank=True, null=True)),
                ('classe_disponibles', models.CharField(blank=True, max_length=100)),
                ('bagage_inclus', models.BooleanField(default=False)),
                ('terminal_depart', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal_arrive', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_offre', models.CharField(choices=[('PACKAGE', 'Package'), ('FLIGHT', 'Flight'), ('ACCOM', 'Accommodation')], default='PACKAGE', max_length=20)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.PositiveIntegerField(default=1)),
                ('politique_remboursement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.accommodation')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.flight')),
            ],
        ),
    ]
