# Generated by Django 5.2.6 on 2025-11-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_destination', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('saison', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='flight',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='prix_base',
            new_name='prix_par_personne',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='politique_remboursement',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='type_offre',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='offer',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='offres/default.jpg', upload_to='offres/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='titre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='offer',
            name='nom_destinations',
            field=models.ManyToManyField(to='offers.destination'),
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
